WITH 
	Forecast AS 
	(
		SELECT
			SF.WERKS AS SITE,
			SF.MATNR AS DISPLAY,
			SUM(CASE WHEN SF.FCSTDATE = CURRENT_DATE THEN SF.QUANTITY ELSE 0 END) AS DAY1,
    		SUM(CASE WHEN SF.FCSTDATE = ADD_DAYS(CURRENT_DATE, 1) THEN SF.QUANTITY ELSE 0 END) AS DAY2,
		    SUM(CASE WHEN SF.FCSTDATE = ADD_DAYS(CURRENT_DATE, 2) THEN SF.QUANTITY ELSE 0 END) AS DAY3,
		    SUM(CASE WHEN SF.FCSTDATE = ADD_DAYS(CURRENT_DATE, 3) THEN SF.QUANTITY ELSE 0 END) AS DAY4
		FROM 
			CONSUMPTION_UK.UK_E21_ZD2FTS_SFCST_CC_V AS SF
		INNER JOIN
			CONSUMPTION_UK.UK_E21_WRF1_CC_V AS WRF1
			ON SF.WERKS = WRF1.LOCNR
		INNER JOIN 
			CONSUMPTION_UK.UK_E21_ZD2FORDERAREAMAT_CC_V AS OA
			ON OA.MATNR = SF.MATNR
			AND REPLACE(OA.WERKS, 'D', 'R') = WRF1.VKBUR_WRK
		WHERE
			WRF1.VKBUR_WRK IN ('CR02', 'CR06', 'CR08', 'CR09', 'CR11')
			AND WRF1.LOCNR NOT LIKE 'CD%'
			AND SF.FCSTDATE 
				BETWEEN CURRENT_DATE
				AND ADD_DAYS(CURRENT_DATE, 3)
		GROUP BY
			SF.MATNR,
			SF.WERKS
	)
	
	,Generic AS 
	(
		SELECT DISTINCT
			BOM_DISP.MATNR AS NONTRIMDISPLAY,
			LTRIM(BOM_DISP.MATNR,0) AS DISPLAY,
			LEFT(LTRIM(BOM_COMP.IDNRK,0),6) AS GENERIC,
			SUM(BOM_COMP.MENGE) AS PACKSZ
		FROM 
			CONSUMPTION_UK.UK_E21_MAST_CC_V AS BOM_DISP
		JOIN 
			CONSUMPTION_UK.UK_E21_STPO_CC_V AS BOM_COMP
			ON BOM_DISP.STLNR = BOM_COMP.STLNR
		GROUP BY 
			BOM_DISP.MATNR, LEFT(LTRIM(BOM_COMP.IDNRK,0),6)
	) , 
	
	Waste AS
	(
		SELECT 
		  VPRIC.ZCPLANT AS Store,
		  LEFT(LTRIM(VPRIC.ZCMATSALE,'0'),6) AS Generic, 
		  SUM( VPRIC.ZKPRICE ) AS Waste_Value
		 
		FROM 
		  CONSUMPTION_UK.UK_BW1_VPRICT002C_CC_V AS VPRIC
		        
		WHERE
		  VPRIC."0CALDAY" = ADD_DAYS( CURRENT_DATE , -1 )
		  AND VPRIC."0INFOPROV" IN ( 'APRICM005' )
		  AND VPRIC.ZCSAL_ORG IN ('7997')
		  AND VPRIC.ZCDIST_CH = '10'
		  AND VPRIC.ZCMATSALE IS NOT NULL
		  AND ZCPLANT__ZCLSALOFF IN ('CR02', 'CR06', 'CR08', 'CR09', 'CR11')
		  AND VPRIC.ZCPRCHTYP IN ('02','03','04','05','11','13','14')
		 
		GROUP BY
			VPRIC.ZCPLANT,
			LEFT(LTRIM(VPRIC.ZCMATSALE,'0'),6)
	)
	
SELECT
	TO_DATE(ADD_DAYS(LEFT(ML.PLANNINGDATE,8), 1)) AS ORDERDATE,
	REPLACE(SITES.VKBUR_WRK,'R','D') AS REGION,
	OA.OAID AS OA_ID,
	OA.OA_DESC AS OA_DESC,
	OA.MATKL AS CAT_ID,
	OA.WGBEZ AS CAT_DESC,
	OA.MAKTX AS PRODUCT_DESC,
	Generic.GENERIC AS GENERIC,
	LTRIM(ML.MATNR,0) AS DISPLAY,
	ML.LOCNO AS SITE,
	ML.MAABC AS ABC,
	ML.PROSL AS PROF_SL,

	CASE 
		WHEN ML.PROREPL = 'ESC_ST_STA' THEN '0'
		WHEN ML.PROREPL = 'ESC_ST_Y' THEN '0'
		WHEN ML.PROREPL = 'ST_0125' THEN '12.5'
		WHEN ML.PROREPL = 'ESC_ST_025' THEN '25'
		WHEN ML.PROREPL = 'ESC_ST_05' THEN '50'
		WHEN ML.PROREPL = 'ESC_ST_075' THEN '75'
		WHEN ML.PROREPL = 'ESC_ST_DEF' THEN '100'
		WHEN ML.PROREPL = 'ESC_ST_125' THEN '125'
		WHEN ML.PROREPL = 'ESC_ST_15' THEN '150'
		WHEN ML.PROREPL = 'ESC_ST_175' THEN '175'
		ELSE ML.PROREPL
	END AS PROF_DYN,
	CASE 
		WHEN ML.MINSTOCK = FRP_MINSTOCK THEN 'STATIC'
		ELSE 'DYNAMIC'
	END AS MIN_TYPE,
	
	ML.FRP_MINSTOCK AS FRP_MIN,
	ML.CLASSMEAN AS CLASSMEAN, -- Exponentially smoothed average weekly sales
	ML.STOCK AS STOCK, 
	Generic.PACKSZ AS PACKSZ,
	Forecast.Day1 * PACKSZ AS DAY1,
	Forecast.Day2 * PACKSZ AS DAY2,
	Forecast.Day3 * PACKSZ AS DAY3,
	Forecast.Day4 * PACKSZ AS DAY4,
	COALESCE(Waste.Waste_Value, 0) AS LOSS_VAL_YDAY,
	ML.FRP_ORDER AS FRP_ORDER,
	ML.UDF_STATUS AS UDF_STATUS,
	COALESCE(NULLIF(ML.SHLF_LFE_REQ_MIN, 0) / 240000, 0) AS SHELFLIFE
	
FROM 
	CONSUMPTION_UK.UK_S21_ZD2FFREMATLOCFRP_CC_V AS ML
	
INNER JOIN 
	CONSUMPTION_UK.UK_E21_ZD2FCORDERASSIGN_CC_V AS OA 
	ON ML.LOCNOFR = OA.WERKS
	AND LTRIM(ML.MATNR,0) = LTRIM(OA.MATNR,0)
INNER JOIN 
	CONSUMPTION_UK.UK_E21_WRF1_CC_V AS SITES
	ON ML.LOCNO = SITES.LOCNR
LEFT JOIN 
	Forecast 
	ON OA.MATNR = Forecast.DISPLAY
	AND ML.LOCNO = Forecast.SITE
LEFT JOIN 
	Generic
	ON OA.MATNR = Generic.NONTRIMDISPLAY
LEFT JOIN
	Waste
	ON ML.LOCNO = Waste.Store
	AND Generic.GENERIC = Waste.Generic

WHERE 
	TO_DATE(LEFT(ML.PLANNINGDATE,8)) = ADD_DAYS(CURRENT_DATE, -1)
	AND SITES.VKBUR_WRK IN ('CR02','CR06','CR08','CR09','CR11')
	AND SITES.LOCNR NOT LIKE 'CD%'
